var items = [
    {
      name: "Dalas Review",
      gender: "Hombre",
      born: "31 de octubre de 1993",
      race: "Humano",
      description: "Daniel José Santomé Lemus (Santa Cruz de Tenerife, 31 de octubre de 1993), más conocido como Dalai Review, es un youtuber, influencer y escritor español. Nacido en Tenerife, en su juventud se trasladó a vivir a Barcelona para posteriormente trasladarse a Irlanda, que es donde vive actualmente. Es conocido por su canal: «Dalas Review». En la actualidad, es uno de los YouTubers más conocidos de España con 9,9 millones de seguidores.",
      type: "persona",
      img: "https://pbs.twimg.com/profile_images/1287431914450751489/fgKy6CCU_400x400.jpg",
    },
    {
      name: "Lizy P",
      gender: "Mujer",
      born: "25 de noviembre de 1982",
      race: "Humana",
      description: "Dámaris Pérez, mejor conocida como Lizy P es una youtuber española nacida en Barcelona. Lizy estudió logopedia en la universidad de Barcelona y también estudió chino mandarín, idioma que actualmente maneja a la perfección. Es una superestrella de YouTube gracias a sus videos de belleza, maquillaje, peinados, videos de hazlo-tú-mismo y estilo de vida.",
      type: "persona",
      img: "https://yt3.ggpht.com/ytc/AKedOLTcBrv4FsuZw_YNosU57ePcNqM7hx2LUIaQ-WDUMh8=s900-c-k-c0x00ffffff-no-rj",
    },
    {
      name: "Ariann Music",
      gender: "Mujer",
      born: "11 de abril de 2006",
      race: "Humana",
      description: "Ariadna Cabrero Lemus (Santa Cruz de Tenerife, España) o Ariann Music, es la hermana de DalasReview. Ella estudió clases de piano y violonchelo al mismo tiempo que danza, teatro y técnica vocal. Ella comenzó su canal de YouTube el 19 de julio del año 2014, y subió su primer vídeo el 11 de agosto de ese mismo año. Conocida por su canal Ariann Music, un canal de música, coreografías y covers.",
      type: "persona",
      img: "https://yt3.ggpht.com/ytc/AKedOLTxMgTJBGWEcDZBzjKoLNLhpzV5AlmUZA5-h7Sc1ek=s900-c-k-c0x00ffffff-no-rj",
    },
    {
      name: "César Abril",
      gender: "Hombre",
      born: "15 de abril de 2003",
      race: "Humano",
      description: "Es un famoso youtuber que hace vlogs, retos, tags y vídeos de temas variados como gameplays. Nació en Tenerife España el 2 de abril de 2003 y actualmente es uno de los youtubers más famosos de su país.",
      type: "persona",
      img: "https://yt3.ggpht.com/ytc/AKedOLRmaUfkRPMVyE95-m_LWI_6jMQL6EhPD5OC5Y21cg=s900-c-k-c0x00ffffff-no-rj",
    },
    {
      name: "WhaTheGame",
      gender: "Hombre",
      born: "31 de octubre de 1993",
      race: "Humano",
      description: "Youtuber que se dedica a copiar todo de Dalas Review, durante años ganó suscriptores a base copiar el estilo de videos de Dalas, su ropa e incluso su cara.",
      type: "persona",
      img: "https://yt3.ggpht.com/ytc/AKedOLQkjzqPXAXrh_wBEKRIRkB9Sp-eYCUi_g2KUZjmvQ=s900-c-k-c0x00ffffff-no-rj",
    },
    {
      name: "Mai",
      gender: "Hembra",
      born: "Desconocida",
      race: "Gata Persa",
      description: "Gata de Dalas y Lizy P, se rumora de que Mai prefiere a Dalas antes que a su dueña.",
      type: "animal",
      img: "https://pbs.twimg.com/profile_images/1010351051424215040/eSB9rf6L.jpg",
    },
    {
      name: "Guapa",
      gender: "Macho",
      born: "Desconocida",
      race: "Pogona",
      description: "Es un macho, pero se quedó así el nombre. Es un tipo de reptil, estos reptiles son animales muy buenos como mascotas.",
      type: "animal",
      img: "https://pbs.twimg.com/media/DW3nhdQX0AELcdq.jpg",
    },
    {
      name: "Lol",
      gender: "Macho",
      born: "Desconocida",
      race: "Pomerania",
      description: "Lol, es un perro de raza, es muy pequeño y le gusta correr por todos lados, su dueña es lizy, y también dalas, tiene un año de edad y el color de su pelaje es un color vainilla. Dalas dice que es de origen ruso",
      type: "animal",
      img: "http://pm1.narvii.com/6976/44693c499e9cac9ed1c5ee07b648ba65341a2c8fr1-1080-1140v2_00.jpg",
    },
    {
      name: "Argos",
      gender: "Macho",
      born: "Desconocida",
      race: "Galgo",
      description: "Un perro de ojos azules, fue adoptado por Dalas cuando era pequeño, su pelaje recuerda a una vaca.",
      type: "animal",
      img: "https://pbs.twimg.com/media/Dn0V_SGXoAALWZc.jpg",
    },
    {
      name: "Silla Gamer",
      gender: "Silla",
      born: "Desconocida",
      race: "Gamer",
      description: "La silla gamer de Dalas, sabe bailar.",
      type: "objeto",
      img: "http://pm1.narvii.com/6657/b3a201e3e57b9994ea69580d3729716dfde98050_00.jpg",
    },
    {
      name: "Katana",
      gender: "Katana",
      born: "Desconocida",
      race: "Japonesa",
      description: "Arma letal 100% real no fake utilizada para intimidar y cortar gente.",
      type: "objeto",
      img: "https://i.ytimg.com/vi/HrPTIbjmyjI/mqdefault.jpg",
    },
    {
      name: "Mini",
      gender: "Mini",
      born: "Desconocida",
      race: "Mini",
      description: "El mini, la droga de los pambisitos.",
      type: "objeto",
      img: "https://i.ytimg.com/vi/MD1om0Cx7hs/maxresdefault.jpg",
    },
    
    
    
  ]
export {items};